package presentation;

import business.Cliente;
import business.Conta;
import business.Movimento;
import java.awt.Color;
import java.awt.Component;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import persistence.DBDataManager;

/**
 *
 * @author Karina
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private DBDataManager db;
    private Cliente cliente;
    private Conta contaAtual;
    private boolean isResetting = false;

    /**
     * Creates new form TelaPrincipal
     *
     * @param c
     */
    public TelaPrincipal(Cliente c) {

        try {
            db = new DBDataManager();
            cliente = c;

            initComponents();
            initCliente();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     *
     */
    public void initCliente() {

       

        try {
            isResetting = true;
            
            cliente = db.loadCliente(cliente.getId());
            
            contaAtual = null;

            this.panelContasCliente1.setCliente(cliente);

            for (Conta c : cliente.getContas()) {

                if (c.getTipo().equals(Conta.Tipo.POUPANCA)) {
                    esconderComponente(panelCriarContaPoupanca, true);
                }

            }
            
            cbxTipoConta.removeAllItems();
            cbxContaOrigem.removeAllItems();
            
            for (Conta conta : cliente.getContas()) {
                cbxTipoConta.addItem(conta.getTipo().toString());
                cbxContaOrigem.addItem(conta.getTipo().toString());
            }

            labelNomeHome.setText("Olá " + cliente.getNome() + "!");
            txtNomePerfil.setText(cliente.getNome());
            txtEmailPerfil.setText(cliente.getEmail());
            txtEnderecoPerfil.setText(cliente.getEndereco());

            atualizaGrid();
            isResetting = false;
            
            cbxTipoConta.setSelectedIndex(0);  
            cbxContaOrigem.setSelectedIndex(0);
            
            cbxTipoContaItemStateChanged(null);
            

        } catch (Exception e) {
            MessageBox.showError(e);
        }

    }

    void isEnter(JPanel btn) {
        btn.setBackground(new Color(153, 153, 255));

    }

    void isExit(JPanel btn) {
        btn.setBackground(new Color(204, 0, 204));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        PanelHeader = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        labelHome = new javax.swing.JLabel();
        panelTranfer = new javax.swing.JPanel();
        labelTranfer = new javax.swing.JLabel();
        panelSaldo = new javax.swing.JPanel();
        labelSaldo = new javax.swing.JLabel();
        panelPerfil = new javax.swing.JPanel();
        labelPerfil = new javax.swing.JLabel();
        panelSair = new javax.swing.JPanel();
        labelSair = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panelTranferTela = new javax.swing.JPanel();
        labelNomeHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMovimentosHome = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNumeroContaHome = new javax.swing.JLabel();
        labelSaldoHome = new javax.swing.JLabel();
        cbxTipoConta = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        panelTransfer = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContaDestino = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtValorTransferir = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        cbxContaOrigem = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTranfer = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelCriarContaPoupanca = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelNumeroContaPoupanca = new javax.swing.JLabel();
        btnCriarContaPoupança = new javax.swing.JButton();
        panelContasCliente1 = new presentation.PanelContasCliente();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNomePerfil = new javax.swing.JTextField();
        txtEmailPerfil = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEnderecoPerfil = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();
        btnEncerrarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBase.setBackground(new java.awt.Color(204, 0, 204));
        panelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeader.setBackground(new java.awt.Color(204, 0, 204));

        labelTitulo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Home Kbank");

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                .addContainerGap(634, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(410, 410, 410))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(21, 21, 21))
        );

        panelBase.add(PanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        panelHome.setBackground(new java.awt.Color(204, 0, 204));
        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHomeMouseExited(evt);
            }
        });

        labelHome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        labelHome.setForeground(new java.awt.Color(255, 255, 255));
        labelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        labelHome.setText("Home");
        labelHome.setMaximumSize(new java.awt.Dimension(0, 15));
        labelHome.setMinimumSize(new java.awt.Dimension(0, 15));
        labelHome.setName(""); // NOI18N
        labelHome.setPreferredSize(null);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(labelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBase.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 280, -1));

        panelTranfer.setBackground(new java.awt.Color(204, 0, 204));
        panelTranfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTranferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTranferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTranferMouseExited(evt);
            }
        });

        labelTranfer.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        labelTranfer.setForeground(new java.awt.Color(255, 255, 255));
        labelTranfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money-transfer.png"))); // NOI18N
        labelTranfer.setText("Tranferir");
        labelTranfer.setMaximumSize(new java.awt.Dimension(0, 15));
        labelTranfer.setMinimumSize(new java.awt.Dimension(0, 15));
        labelTranfer.setName(""); // NOI18N
        labelTranfer.setPreferredSize(null);

        javax.swing.GroupLayout panelTranferLayout = new javax.swing.GroupLayout(panelTranfer);
        panelTranfer.setLayout(panelTranferLayout);
        panelTranferLayout.setHorizontalGroup(
            panelTranferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranferLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(labelTranfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );
        panelTranferLayout.setVerticalGroup(
            panelTranferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTranfer, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBase.add(panelTranfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 280, -1));

        panelSaldo.setBackground(new java.awt.Color(204, 0, 204));
        panelSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSaldoMouseExited(evt);
            }
        });

        labelSaldo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        labelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        labelSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profit.png"))); // NOI18N
        labelSaldo.setText("Conta");
        labelSaldo.setMaximumSize(new java.awt.Dimension(0, 15));
        labelSaldo.setMinimumSize(new java.awt.Dimension(0, 15));
        labelSaldo.setName(""); // NOI18N

        javax.swing.GroupLayout panelSaldoLayout = new javax.swing.GroupLayout(panelSaldo);
        panelSaldo.setLayout(panelSaldoLayout);
        panelSaldoLayout.setHorizontalGroup(
            panelSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaldoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(labelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );
        panelSaldoLayout.setVerticalGroup(
            panelSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        panelBase.add(panelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 269, 280, -1));

        panelPerfil.setBackground(new java.awt.Color(204, 0, 204));
        panelPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPerfilMouseExited(evt);
            }
        });

        labelPerfil.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        labelPerfil.setForeground(new java.awt.Color(255, 255, 255));
        labelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resume.png"))); // NOI18N
        labelPerfil.setText("Perfil");
        labelPerfil.setMaximumSize(new java.awt.Dimension(0, 15));
        labelPerfil.setMinimumSize(new java.awt.Dimension(0, 15));
        labelPerfil.setName(""); // NOI18N
        labelPerfil.setPreferredSize(null);

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBase.add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 280, -1));

        panelSair.setBackground(new java.awt.Color(204, 0, 204));
        panelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSairMouseExited(evt);
            }
        });

        labelSair.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        labelSair.setForeground(new java.awt.Color(255, 255, 255));
        labelSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        labelSair.setText("Sair");
        labelSair.setMaximumSize(new java.awt.Dimension(0, 15));
        labelSair.setMinimumSize(new java.awt.Dimension(0, 15));
        labelSair.setName(""); // NOI18N
        labelSair.setPreferredSize(null);

        javax.swing.GroupLayout panelSairLayout = new javax.swing.GroupLayout(panelSair);
        panelSair.setLayout(panelSairLayout);
        panelSairLayout.setHorizontalGroup(
            panelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSairLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(labelSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );
        panelSairLayout.setVerticalGroup(
            panelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSair, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBase.add(panelSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 280, -1));

        labelNomeHome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        labelNomeHome.setText("Olá, Karina!");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel3.setText("Bem vindo ao KBank");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setText("Últimas Transações");

        tableMovimentosHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMovimentosHome);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Saldo Corrente");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nº Conta:");

        labelNumeroContaHome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        labelNumeroContaHome.setForeground(new java.awt.Color(255, 255, 255));
        labelNumeroContaHome.setText("123456789");

        labelSaldoHome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        labelSaldoHome.setForeground(new java.awt.Color(255, 255, 255));
        labelSaldoHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSaldoHome.setText("70.000,00");

        cbxTipoConta.setBackground(new java.awt.Color(102, 102, 102));
        cbxTipoConta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cbxTipoConta.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipoConta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbxTipoConta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoContaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbxTipoConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumeroContaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSaldoHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldoHome)
                    .addComponent(labelNumeroContaHome))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTranferTelaLayout = new javax.swing.GroupLayout(panelTranferTela);
        panelTranferTela.setLayout(panelTranferTelaLayout);
        panelTranferTelaLayout.setHorizontalGroup(
            panelTranferTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranferTelaLayout.createSequentialGroup()
                .addGroup(panelTranferTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranferTelaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelTranferTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(labelNomeHome)))
                    .addGroup(panelTranferTelaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelTranferTelaLayout.setVerticalGroup(
            panelTranferTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranferTelaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelNomeHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranferTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTranferTela, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranferTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atm-card.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nº Conta Destino:");

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Valor a Transferir:");

        btnTransferir.setBackground(new java.awt.Color(204, 0, 204));
        btnTransferir.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exchange.png"))); // NOI18N
        btnTransferir.setText("Transferir");
        btnTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransferirMouseClicked(evt);
            }
        });
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        cbxContaOrigem.setToolTipText("");
        cbxContaOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxContaOrigemItemStateChanged(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Conta Origem:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTransferir))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cbxContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtContaDestino))))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(130, 130, 130))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtValorTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        tableTranfer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTranfer);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(141, 141, 141))
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 874, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bankxs.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel20.setText("KBank");

        jLabel21.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel21.setText("Endereço: Rua das Flores, 18");

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel22.setText("Telefone: 253 856 474");

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel23.setText("E-mail: Kbank@Kbank.com");

        panelCriarContaPoupanca.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Criar Conta Poupança");

        labelNumeroContaPoupanca.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        labelNumeroContaPoupanca.setForeground(new java.awt.Color(255, 255, 255));
        labelNumeroContaPoupanca.setText("Número Conta Poupança");

        btnCriarContaPoupança.setBackground(new java.awt.Color(204, 0, 204));
        btnCriarContaPoupança.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnCriarContaPoupança.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarContaPoupança.setText("Criar Conta Poupança");
        btnCriarContaPoupança.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarContaPoupançaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCriarContaPoupancaLayout = new javax.swing.GroupLayout(panelCriarContaPoupanca);
        panelCriarContaPoupanca.setLayout(panelCriarContaPoupancaLayout);
        panelCriarContaPoupancaLayout.setHorizontalGroup(
            panelCriarContaPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriarContaPoupancaLayout.createSequentialGroup()
                .addGroup(panelCriarContaPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCriarContaPoupancaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(panelCriarContaPoupancaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(labelNumeroContaPoupanca))
                    .addGroup(panelCriarContaPoupancaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnCriarContaPoupança)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelCriarContaPoupancaLayout.setVerticalGroup(
            panelCriarContaPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriarContaPoupancaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(labelNumeroContaPoupanca)
                .addGap(18, 18, 18)
                .addComponent(btnCriarContaPoupança, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel19))
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCriarContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContasCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addComponent(panelCriarContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(panelContasCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder-4-avatar-2754580_120522.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel25.setText("Nome:");

        jLabel26.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel26.setText("E-mail:");

        jLabel27.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel27.setText("Endereço:");

        btnEditarPerfil.setBackground(new java.awt.Color(204, 0, 204));
        btnEditarPerfil.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil.setText("Editar");
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        btnEncerrarConta.setBackground(new java.awt.Color(204, 0, 204));
        btnEncerrarConta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnEncerrarConta.setForeground(new java.awt.Color(255, 255, 255));
        btnEncerrarConta.setText("Encerrar Conta");
        btnEncerrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(344, 344, 344))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailPerfil)
                            .addComponent(txtNomePerfil)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnderecoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEncerrarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(241, 241, 241))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtEmailPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarPerfil)
                    .addComponent(btnEncerrarConta))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        panelBase.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 36, -1, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_panelHomeMouseClicked

    private void panelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseEntered
        // TODO add your handling code here:
        JPanel btn = panelHome;
        isEnter(btn);
    }//GEN-LAST:event_panelHomeMouseEntered

    private void panelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseExited
        // TODO add your handling code here:
        JPanel btn = panelHome;
        isExit(btn);
    }//GEN-LAST:event_panelHomeMouseExited

    private void panelTranferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTranferMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        labelTitulo.setText("Tranferência");
    }//GEN-LAST:event_panelTranferMouseClicked

    private void panelTranferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTranferMouseEntered
        // TODO add your handling code here:
        JPanel btn = panelTranfer;
        isEnter(btn);
    }//GEN-LAST:event_panelTranferMouseEntered

    private void panelTranferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTranferMouseExited
        // TODO add your handling code here:
        JPanel btn = panelTranfer;
        isExit(btn);
    }//GEN-LAST:event_panelTranferMouseExited

    private void panelSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaldoMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        labelTitulo.setText("Minhas Contas");
    }//GEN-LAST:event_panelSaldoMouseClicked

    private void panelSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaldoMouseEntered
        // TODO add your handling code here:
        JPanel btn = panelSaldo;
        isEnter(btn);
    }//GEN-LAST:event_panelSaldoMouseEntered

    private void panelSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaldoMouseExited
        // TODO add your handling code here:
        JPanel btn = panelSaldo;
        isExit(btn);
    }//GEN-LAST:event_panelSaldoMouseExited

    private void panelPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPerfilMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        labelTitulo.setText("Meu Perfil");
    }//GEN-LAST:event_panelPerfilMouseClicked

    private void panelPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPerfilMouseEntered
        // TODO add your handling code here:
        JPanel btn = panelPerfil;
        isEnter(btn);
    }//GEN-LAST:event_panelPerfilMouseEntered

    private void panelPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPerfilMouseExited
        // TODO add your handling code here:
        JPanel btn = panelPerfil;
        isExit(btn);
    }//GEN-LAST:event_panelPerfilMouseExited

    private void panelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSairMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_panelSairMouseClicked

    private void panelSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSairMouseEntered
        // TODO add your handling code here:
        JPanel btn = panelSair;
        isEnter(btn);
    }//GEN-LAST:event_panelSairMouseEntered

    private void panelSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSairMouseExited
        // TODO add your handling code here:
        JPanel btn = panelSair;
        isExit(btn);
    }//GEN-LAST:event_panelSairMouseExited

    private void cbxTipoContaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoContaItemStateChanged
        
        this.alteraContaAtual(cbxTipoConta);

    }//GEN-LAST:event_cbxTipoContaItemStateChanged

    private void btnTransferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferirMouseClicked
     

    }//GEN-LAST:event_btnTransferirMouseClicked

    private void cbxContaOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxContaOrigemItemStateChanged
       this.alteraContaAtual(cbxContaOrigem);
    }//GEN-LAST:event_cbxContaOrigemItemStateChanged

    private void esconderComponente(JComponent comp, boolean mostrar) {
        for (Component compf : comp.getComponents()) {
            compf.setVisible(!mostrar);
        }
        comp.setVisible(!mostrar);
    }


    private void btnCriarContaPoupançaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarContaPoupançaMouseClicked

        try {
            Conta c = new Conta();
            c.setTipo(Conta.Tipo.POUPANCA);
            c = db.criarContaBancaria(c, cliente, new BigDecimal(0));
            labelNumeroContaPoupanca.setText(c.getNumeroConta());

            initCliente();

        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCriarContaPoupançaMouseClicked

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        // TODO add your handling code here:
        cliente.setNome(txtNomePerfil.getText());
        cliente.setEmail(txtEmailPerfil.getText());
        cliente.setEndereco(txtEnderecoPerfil.getText());

        try {

            cliente = db.editarCliente(cliente);

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        initCliente();

    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnEncerrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarContaActionPerformed
        try {
            // TODO add your handling code here:

            if (MessageBox.showConfirm("Tem certeza que deseja encerrar esta conta?") == 0) {
                db.encerrarConta(cliente.getId());
                Login l = new Login();
                setVisible(false);
                l.setVisible(true);
                dispose();
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEncerrarContaActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:

            Conta destino = db.getContaByNumero(txtContaDestino.getText());

            if (destino != null) {

                db.transferir(contaAtual, destino, new BigDecimal(txtValorTransferir.getText()));
                initCliente();
            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    /**
     * Atualiza movimentos
     */
    public void atualizaGrid() {

        String cols[] = {"Data", "Tipo", "Montante", "D/C", "Saldo"};
        DefaultTableModel dlm = new DefaultTableModel(cols, 0);

        try {

            ArrayList<Movimento> movimentos = db.getMovimentosCliente(cliente);

            for (Movimento m : movimentos) {
                String mv[] = {m.getDataHora().toString(), m.getConta().getTipo().toString(), m.getMontante().toString(), m.getTipo().toString(), m.getSaldo().toString()};
                dlm.addRow(mv);
            }

            tableMovimentosHome.setModel(dlm);
            tableTranfer.setModel(dlm);
        } catch (Exception e) {
            MessageBox.showError(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(new Cliente()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JButton btnCriarContaPoupança;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnEncerrarConta;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<String> cbxContaOrigem;
    private javax.swing.JComboBox<String> cbxTipoConta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelNomeHome;
    private javax.swing.JLabel labelNumeroContaHome;
    private javax.swing.JLabel labelNumeroContaPoupanca;
    private javax.swing.JLabel labelPerfil;
    private javax.swing.JLabel labelSair;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSaldoHome;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTranfer;
    private javax.swing.JPanel panelBase;
    private presentation.PanelContasCliente panelContasCliente1;
    private javax.swing.JPanel panelCriarContaPoupanca;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JPanel panelSair;
    private javax.swing.JPanel panelSaldo;
    private javax.swing.JPanel panelTranfer;
    private javax.swing.JPanel panelTranferTela;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JTable tableMovimentosHome;
    private javax.swing.JTable tableTranfer;
    private javax.swing.JTextField txtContaDestino;
    private javax.swing.JTextField txtEmailPerfil;
    private javax.swing.JTextField txtEnderecoPerfil;
    private javax.swing.JTextField txtNomePerfil;
    private javax.swing.JTextField txtValorTransferir;
    // End of variables declaration//GEN-END:variables

    private void alteraContaAtual(JComboBox<String> comboBox) {
        
        // O setSelectedIndex e addItem das combobox despoletam "change", entrando aqui novamente.
        // por isso mudamos o valor de "isResetting" para true quando nao queremos que entre em ciclo
        if (isResetting) {
            return;
        }
        

        Conta.Tipo tipoSelecionado = null;

        for (Conta.Tipo t : Conta.Tipo.values()) {
            if (comboBox.getSelectedItem().equals(t.toString())) {
                tipoSelecionado = t;
            }
        }

        if (contaAtual == null || !contaAtual.getTipo().equals(tipoSelecionado)) {
            for (Conta conta : cliente.getContas()) {

                if (conta.getTipo().equals(tipoSelecionado)) {
                    contaAtual = conta;
                    break;
                }
            }
        }
        
        
        // vamos por a true para nao voltar a entrar aqui
        isResetting=true;
        cbxTipoConta.setSelectedIndex(comboBox.getSelectedIndex());
        cbxContaOrigem.setSelectedIndex(comboBox.getSelectedIndex());
        
        //vamos voltar a por a false para que volte tudo ao "normal"
        isResetting=false;
        
        labelNumeroContaHome.setText(contaAtual.getNumeroConta());
        labelSaldoHome.setText("€ " + contaAtual.getSaldo().toString());
    }
}
